services:
  app:
    build:
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: client_app
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/sites-available/default
      - ./docker/php/fpm.ini:/usr/local/etc/php/conf.d/fpm.ini
      - ./docker/php/cli.ini:/usr/local/etc/php/conf.d/cli.ini
    ports:
      - "80:80"
    networks:
      - crater
networks:
  crater:
    driver: bridge
