version: '3'

services:
  app:
    build:
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: client_app
    volumes:
      - ./:/var/www
    networks:
      - crater
networks:
  crater:
    driver: bridge
